apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        image: arulkumar1967/rev_mariadb_gke_sb
        name: mysql
        ports:
        - name: mysqlport
          containerPort: 3306
          protocol: TCP
