apiVersion: v1
kind: Service
metadata:
  name: test-service-1
spec:
  type: LoadBalancer
  ports:
  - name: test-service-1
    port: 80
    protocol: TCP
    targetPort: 8090
  selector:
    app: test-app-1
